const getCovidDataMock = () => ({
  dates: {
    '2022-03-12': {
      countries: {
        Afghanistan: {
          date: '2022-03-12',
          id: 'afghanistan',
          links: [
            {
              href: '/api/2022-03-12/country/afghanistan',
              rel: 'self',
              type: 'GET',
            },
          ],
          name: 'Afghanistan',
          name_es: 'Afganistán',
          name_it: 'afghanistan',
          regions: [],
          source: 'John Hopkins University',
          today_confirmed: 156610,
          today_deaths: 7294,
          today_new_confirmed: 58,
          today_new_deaths: 1,
          today_new_open_cases: 57,
          today_new_recovered: 0,
          today_open_cases: 66730,
          today_recovered: 82586,
          today_vs_yesterday_confirmed: 0.0003704839286626793,
          today_vs_yesterday_deaths: 0.00013711778417668796,
          today_vs_yesterday_open_cases: 0.0008549187827155968,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 156552,
          yesterday_deaths: 7293,
          yesterday_open_cases: 66673,
          yesterday_recovered: 82586,
        },
        Albania: {
          date: '2022-03-12',
          id: 'albania',
          links: [
            {
              href: '/api/2022-03-12/country/albania',
              rel: 'self',
              type: 'GET',
            },
          ],
          name: 'Albania',
          name_es: 'Albania',
          name_it: 'Albania',
          regions: [],
          source: 'John Hopkins University',
          today_confirmed: 193269,
          today_deaths: 2997,
          today_new_confirmed: 194,
          today_new_deaths: 7,
          today_new_open_cases: 187,
          today_new_recovered: 0,
          today_open_cases: 59929,
          today_recovered: 130343,
          today_vs_yesterday_confirmed: 0.0010047908843713316,
          today_vs_yesterday_deaths: 0.00234113712374584,
          today_vs_yesterday_open_cases: 0.0031301262093670346,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 193075,
          yesterday_deaths: 2990,
          yesterday_open_cases: 59742,
          yesterday_recovered: 130343,
        },
        Algeria: {
          date: '2022-03-12',
          id: 'algeria',
          links: [
            {
              href: '/api/2022-03-12/country/algeria',
              rel: 'self',
              type: 'GET',
            },
          ],
          name: 'Algeria',
          name_es: 'Argelia',
          name_it: 'algeria',
          regions: [],
          source: 'John Hopkins University',
          today_confirmed: 208104,
          today_deaths: 5991,
          today_new_confirmed: 134,
          today_new_deaths: 7,
          today_new_open_cases: 127,
          today_new_recovered: 0,
          today_open_cases: 82961,
          today_recovered: 119152,
          today_vs_yesterday_confirmed: 0.0006443237005337998,
          today_vs_yesterday_deaths: 0.0011697860962567308,
          today_vs_yesterday_open_cases: 0.0015331868556389683,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 207970,
          yesterday_deaths: 5984,
          yesterday_open_cases: 82834,
          yesterday_recovered: 119152,
        },
        Andorra: {
          date: '2022-03-12',
          id: 'andorra',
          links: [
            {
              href: '/api/2022-03-12/country/andorra',
              rel: 'self',
              type: 'GET',
            },
          ],
          name: 'Andorra',
          name_es: 'Andorra',
          name_it: 'Andorra',
          regions: [],
          source: 'John Hopkins University',
          today_confirmed: 15907,
          today_deaths: 130,
          today_new_confirmed: 88,
          today_new_deaths: 0,
          today_new_open_cases: 88,
          today_new_recovered: 0,
          today_open_cases: 1361,
          today_recovered: 14416,
          today_vs_yesterday_confirmed: 0.005562930653012277,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_open_cases: 0.06912804399057348,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 15819,
          yesterday_deaths: 130,
          yesterday_open_cases: 1273,
          yesterday_recovered: 14416,
        },
        Angola: {
          date: '2022-03-12',
          id: 'angola',
          links: [
            {
              href: '/api/2022-03-12/country/angola',
              rel: 'self',
              type: 'GET',
            },
          ],
          name: 'Angola',
          name_es: 'Angola',
          name_it: 'angola',
          regions: [],
          source: 'John Hopkins University',
          today_confirmed: 64913,
          today_deaths: 1727,
          today_new_confirmed: 0,
          today_new_deaths: 0,
          today_new_open_cases: -265,
          today_new_recovered: 265,
          today_open_cases: 23339,
          today_recovered: 39847,
          today_vs_yesterday_confirmed: 0.0,
          today_vs_yesterday_deaths: 0.0,
          today_vs_yesterday_open_cases: -0.011226910693102887,
          today_vs_yesterday_recovered: 0.00669496235662681,
          yesterday_confirmed: 64913,
          yesterday_deaths: 1727,
          yesterday_open_cases: 23604,
          yesterday_recovered: 39582,
        },
        Argentina: {
          date: '2021-11-15',
          id: 'argentina',
          links: [
            {
              href: '/api/2022-03-12/country/argentina',
              rel: 'self',
              type: 'GET',
            },
          ],
          name: 'Argentina',
          name_es: 'Argentina',
          name_it: 'Argentina',
          regions: [
            {
              date: '2020-12-02',
              id: 'misiones',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/misiones',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Misiones',
              name_es: 'Misiones',
              name_it: 'Misiones',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'corrientes',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/corrientes',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Corrientes',
              name_es: 'Corrientes',
              name_it: 'Corrientes',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'san_juan',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/san_juan',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'San Juan',
              name_es: 'San Juan',
              name_it: 'San Juan',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'san_luis',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/san_luis',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'San Luis',
              name_es: 'San Luis',
              name_it: 'San Luis',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'jujuy',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/jujuy',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Jujuy',
              name_es: 'Jujuy',
              name_it: 'Jujuy',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'chaco',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/chaco',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Chaco',
              name_es: 'Chaco',
              name_it: 'Chaco',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'tucuman',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/tucuman',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Tucumán',
              name_es: 'Tucumán',
              name_it: 'Tucumán',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'salta',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/salta',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Salta',
              name_es: 'Salta',
              name_it: 'Salta',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'catamarca',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/catamarca',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Catamarca',
              name_es: 'Catamarca',
              name_it: 'Catamarca',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'santa_fe',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/santa_fe',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Santa Fe',
              name_es: 'Santa Fe',
              name_it: 'Santa Fe',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'neuquen',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/neuquen',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Neuquén',
              name_es: 'Neuquén',
              name_it: 'Neuquén',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'santiago_del_estero',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/santiago_del_estero',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Santiago del Estero',
              name_es: 'Santiago del Estero',
              name_it: 'Santiago del Estero',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'entre_rios',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/entre_rios',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Entre Ríos',
              name_es: 'Entre Ríos',
              name_it: 'Entre Ríos',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'formosa',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/formosa',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Formosa',
              name_es: 'Formosa',
              name_it: 'Formosa',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'santa_cruz',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/santa_cruz',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Santa Cruz',
              name_es: 'Santa Cruz',
              name_it: 'Santa Cruz',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'ciudad_autonoma_de_buenos_aires',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/ciudad_autonoma_de_buenos_aires',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Ciudad Autónoma de Buenos Aires',
              name_es: 'Ciudad Autónoma de Buenos Aires',
              name_it: 'Ciudad Autónoma de Buenos Aires',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'tierra_del_fuego',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/tierra_del_fuego',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Tierra del Fuego',
              name_es: 'Tierra del Fuego',
              name_it: 'Tierra del Fuego',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'rio_negro',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/rio_negro',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Río Negro',
              name_es: 'Río Negro',
              name_it: 'Río Negro',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'chubut',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/chubut',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Chubut',
              name_es: 'Chubut',
              name_it: 'Chubut',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'mendoza',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/mendoza',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Mendoza',
              name_es: 'Mendoza',
              name_it: 'Mendoza',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'la_rioja',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/la_rioja',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'La Rioja',
              name_es: 'La Rioja',
              name_it: 'La Rioja',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'la_pampa',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/la_pampa',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'La Pampa',
              name_es: 'La Pampa',
              name_it: 'La Pampa',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'cordoba',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/cordoba',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Córdoba',
              name_es: 'Córdoba',
              name_it: 'Córdoba',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
            {
              date: '2020-12-02',
              id: 'buenos_aires',
              links: [
                {
                  href: '/api/2022-03-12/country/argentina/region/buenos_aires',
                  rel: 'self',
                  type: 'GET',
                },
              ],
              name: 'Buenos Aires',
              name_es: 'Buenos Aires',
              name_it: 'Buenos Aires',
              source: 'Ministerio de Salud Argentina',
              sub_regions: [],
              today_confirmed: 0,
              today_deaths: 0,
              today_new_confirmed: 0,
              today_new_deaths: 0,
              today_new_open_cases: 0,
              today_new_recovered: 0,
              today_open_cases: 0,
              today_recovered: 0,
              today_vs_yesterday_confirmed: null,
              today_vs_yesterday_deaths: null,
              today_vs_yesterday_open_cases: null,
              today_vs_yesterday_recovered: null,
              yesterday_confirmed: 0,
              yesterday_deaths: 0,
              yesterday_open_cases: 0,
              yesterday_recovered: 0,
            },
          ],
          source: 'Ministerio de Salud Argentina',
          today_confirmed: 5307159,
          today_deaths: 116250,
          today_new_confirmed: 1417,
          today_new_deaths: 18,
          today_new_open_cases: 1399,
          today_new_recovered: 0,
          today_open_cases: 560473,
          today_recovered: 4630436,
          today_vs_yesterday_confirmed: 0.00026706914885799016,
          today_vs_yesterday_deaths: 0.00015486268841624629,
          today_vs_yesterday_open_cases: 0.002502352103657124,
          today_vs_yesterday_recovered: 0.0,
          yesterday_confirmed: 5305742,
          yesterday_deaths: 116232,
          yesterday_open_cases: 559074,
          yesterday_recovered: 4630436,
        },
      },
    },
  },
});

export default getCovidDataMock;
